export const serverStringErrorsAndCodes = {
  invalidEmailOrPassword: { message: "Email ou senha inválidos", code: 400 },
  userAlreadyExists: { message: "Usuário existente", code: 400 },
  userNotFound: { message: "Usuário não encontrado", code: 404 },
  invalidToken: { message: "Token inválido ou expirado", code: 401 },
  unauthorizedAccess: { message: "Acesso não autorizado", code: 403 },
  tokenNotProvided: { message: "Token não fornecido", code: 401 },
  eventAlreadyExists: { message: "Evento já existente", code: 400 },
  eventNotFound: { message: "Evento não encontrado", code: 404 },
  ticketAlreadyExists: { message: "Ingresso já existente", code: 400 },
  ticketNotFound: { message: "Ingresso não encontrado", code: 404 },
  invalidPriceOrAmount: { message: "Preço ou quantidade inválidos", code: 400 },
  promotionAlreadyExists: { message: "Promoção já existente", code: 400 },
  promotionNotFound: { message: "Promoção não encontrada", code: 404 },
  invalidDiscount: { message: "Desconto inválido", code: 400 },
  emailNotSent: { message: "Email não enviado", code: 500 },
  registerFailed: {
    message: "Falha no registro",
    code: 400,
  },
  invalidPromoCode: { message: "Código de promoção inválido", code: 400 },
};
